### ISSUE TITLE
Add extra metadata to container spec

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/konf#23]
We need to add extra metadata to a container spec, is there a way to easily do this with konf.

In our case for a reason when pods get generated they don't use the only docker creds available, I had to add an extra parameter: 
```
          imagePullSecrets:
          - name: regcred
```

**Comment by nottrobin** [comment]
This sounds like a reasonable feature request, but could you please elaborate a little more on the reason so we know how to design it?

**Comment by jkfran** [comment]
Why do you need this kind of secret in your application? It could be very dangerous if we leaked it, the account have write permissions to our private docker registry.

**Comment by anthonydillon** [comment]
To be discussed in the infra guild meeting on the 28th of March.

**Comment by jpmartinspt** [comment]
@tbille is going to try and change the k8s cluster from workplace to behave has the other ones, instead of doing this fix.

**Comment by jkfran** [comment]
Hi, this is very old, but I had this problem today with the new PS5 cluster. This is what was missing in the new cluster:
```
microk8s.kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "registry-access"}]}' --namespace default
```

I had to do it for the staging and production namespaces.

This is something we were already doing in the local-qa script: https://github.com/canonical/konf/blob/00e89099ef8361e26df2e0f336c8651d333bb9fa/qa-deploy#L65
