### ISSUE TITLE
Ingress version "networking.k8s.io/v1beta1" is broken on k8s version v1.20+

### ISSUE THREAD

**Issue by goulinkh** [canonical-web-and-design/konf#30]
PS5 and WPE k8s clusters have more up to date versions so konf output isn't accepted anymore by k8s.
I had to replace this part from the output manually:
![image](https://user-images.githubusercontent.com/36013798/174274773-b96542cd-56be-4e17-9404-3a36e6c9566c.png)

**Comment by carkod** [comment]
@goulinkh can you estimate? @nottrobin should we do this on Systems tribe or maintenance sprint?
